workplace_admin_homepage:
    path:     /
    defaults: { _controller: WorkplaceAdminBundle:Default:index }

index:
    path:     /index
    defaults: { _controller: WorkplaceAdminBundle:Admin:index }
