workplace_web_portal_homepage:
  path: /{lang}
  defaults: { _controller: WorkplaceWebBundle:Portal:index, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_portal_about:
  path: /about/{lang}
  defaults: { _controller: WorkplaceWebBundle:Portal:about, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_portal_contacts:
  path: /contacts/{lang}
  defaults: { _controller: WorkplaceWebBundle:Portal:contacts, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_account_index:
  path: /account/{lang}
  defaults: { _controller: WorkplaceWebBundle:Account:index, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_account_tasks:
  path: /account/tasks/{lang}
  defaults: { _controller: WorkplaceWebBundle:Account:tasks, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_account_calendar:
  path: /account/calendar/{lang}
  defaults: { _controller: WorkplaceWebBundle:Account:calendar, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru

workplace_web_account_map:
  path: /account/map/{lang}
  defaults: { _controller: WorkplaceWebBundle:Account:map, lang: ru }
  methods: [GET]
  requirements:
    lang: en|fr|ru
