Workplace\UsersBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Workplace\UsersBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
